apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mxqgo2j8j-nodejs 
  janus-idp.io/tekton: mxqgo2j8j-nodejs
  backstage.io/kubernetes-id: mxqgo2j8j-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mxqgo2j8j-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  